CREATE DATABASE IF NOT EXISTS cdc_test;
USE cdc_test;

CREATE TABLE IF NOT EXISTS dem_test (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    customer_name VARCHAR(128) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount_cents BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cdc_watermark (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    watermark_value CHAR(36) NOT NULL
) ENGINE=InnoDB;

INSERT INTO cdc_watermark (id, watermark_value)
VALUES (1, '00000000-0000-0000-0000-000000000000')
ON DUPLICATE KEY UPDATE watermark_value = VALUES(watermark_value);

CREATE USER IF NOT EXISTS 'cdc'@'%' IDENTIFIED BY 'cdc_pass';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'cdc'@'%';
GRANT INSERT, UPDATE, DELETE ON cdc_test.* TO 'cdc'@'%';
FLUSH PRIVILEGES;
