CREATE DATABASE IF NOT EXISTS cdc_test;
USE cdc_test;

CREATE TABLE IF NOT EXISTS dem_test (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE USER IF NOT EXISTS 'cdc'@'%' IDENTIFIED BY 'cdc_pass';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'cdc'@'%';
GRANT INSERT, UPDATE, DELETE ON cdc_test.* TO 'cdc'@'%';
FLUSH PRIVILEGES;
